package.json

Add a preview button on the top-right when editting .typ file

feat: preview icon

---

index.html

Also make it work with Ctrl+scrolling / panel (drag) resizing.

Adjust the initial canvas width according to the panel width

---

addons/vscode/README.md
addons/vscode/package.json
addons/vscode/src/extension.ts

features mentioned in #8
possibly fix resource leak #5

add output channel and config for refresh type

---

addons/vscode/index.html
src/main.rs

Allow incremental update of pages.

performance: make page update aware of visibility

---

addons/vscode/src/extension.ts
src/main.rs

Choose websocket port automatically. fix #11

feat: automatically choose port

---

addons/vscode/CHANGELOG.md
addons/vscode/LICENSE
addons/vscode/README.md
addons/vscode/package.json
src/main.rs

fix: exit server when client disconnects

---

.github/workflows/release.yml
addons/vscode/CHANGELOG.md
addons/vscode/README.md
addons/vscode/package.json

ci: add openvsx

---

addons/vscode/CHANGELOG.md
addons/vscode/README.md
addons/vscode/package.json
addons/vscode/src/extension.ts

fix: inherit env

---

addons/frontend/src/svg-patch.test.ts
addons/frontend/src/svg-patch.ts

work with [typst.ts#158](https://github.com/Myriad-Dreamin/typst.ts/pull/158).

dev: recursive replace svg reuse

---

addons/frontend/src/svg-patch.test.ts
addons/frontend/src/svg-patch.ts

It cannot calculate swap operations well, so new SVG patcher switches to simulating approach, which has poorer performance but less likely to be bug-prone.
Related testcases are also added to prevent bug recursion.

fix: do simulate and swap SVG elements

---

addons/frontend/src/svg-debug-info.ts
addons/frontend/src/svg-doc.ts

fix: grab source mapping from the correct element

---

addons/vscode/src/extension.ts

I'm unsure that whether it will ignore user's shortcuts.

dev: also ignore scrolling request from key event

---

addons/frontend/src/svg-patch.test.ts
addons/frontend/src/svg-patch.ts

+ to optimize swaps
See snapshot testing to understand this optimization.

dev: use resources from left to right

---

Cargo.toml
README.md
addons/frontend/src/svg-patch.ts
addons/vscode/README.md
addons/vscode/package.json

fix: upgrade to latest typst.ts

---

Cargo.toml
addons/vscode/src/extension.ts
src/main.rs

This PR aims to improve typst-preview's watching dirty files (#24) and solve a related issue at the same time (#60).
+ [x] remove code related to shadow files mapping
+ [ ] refactor code

feat: watch dirty files in memory

---

addons/frontend/src/svg-doc.ts
addons/vscode/README.md

feat: scale to cursor

---

addons/vscode/package.json

fix #87, thanks @enivex for finding this bug!

fix: add description for typst-preview.scrollSync

---

Cargo.lock
Cargo.toml
addons/vscode/CHANGELOG.md
addons/vscode/README.md
addons/vscode/package.json

- Bugfix: fix a subtle rendering issue, [typst.ts#306](https://github.com/Myriad-Dreamin/typst.ts/pull/306).

bump to v0.7.3

---

src/actor/typst.rs

fix: provide better error message when fail to watch files

---

src/args.rs
src/main.rs

https://github.com/Enter-tainer/typst-preview/issues/93#issuecomment-1690318794

feat: always serve static file to avoid confusion

---

Cargo.lock
Cargo.toml
addons/frontend/package.json
addons/frontend/src/main.js
addons/frontend/yarn.lock

fix https://github.com/Myriad-Dreamin/typst.ts/pull/316

build: upgrade typst.ts 0.4.0-rc2

---

Cargo.toml
README.md
addons/vscode/src/extension.ts
src/actor/typst.rs
src/args.rs
src/main.rs

improve cli args for standalone usage

---

addons/vscode/package.json
addons/vscode/src/extension.ts
addons/vscode/yarn.lock

feat: support vscode variable in config

---

addons/vscode/src/extension.ts

fix: cannot preview multiple files at once

---

.vscode/tasks.json
Cargo.lock
Cargo.toml
addons/frontend/package.json
addons/frontend/src/main.js
addons/frontend/src/svg-doc.ts
addons/frontend/yarn.lock
src/actor/typst.rs
src/main.rs

fix https://github.com/Enter-tainer/typst-preview/issues/105 and fix https://github.com/Enter-tainer/typst-preview/issues/111

bump to v0.8.0

---

addons/frontend/src/main.js

possibly fix #119.
There is a race condition in current code. Messages comes from the server may comes out of order because of `Promise.then`

fix: set ws's binary type to array buffer to avoid possible race condition

---

addons/frontend/index.html

fix bad showing browser page with the evil dark reader, cooperating with #120. fix #93

dev(frontend): disable too smart dark reader

---

Cargo.lock
Cargo.toml
src/actor/typst.rs
src/main.rs

This problem is found in various editors, such as vscode and neovim.

dev: use upstream watch & notify actor

---

addons/vscode/src/extension.ts

fix: retain webview ctx when hidden

---

Cargo.lock
Cargo.toml
build.rs
src/args.rs

feat: add version string for binary

---

addons/vscode/package.json
addons/vscode/src/extension.ts

fix #133 
https://github.com/clangd/vscode-clangd/pull/177/files

add show logs command and button when crashes

---

addons/frontend/index.html
addons/frontend/src/main.js
addons/frontend/src/svg-doc.ts
addons/frontend/src/typst.css

+ shaking border width
+ shaking border height
+ shaking horizontal scrollbar

dev: try to avoid calculation error that casues

---

.github/workflows/gh-pages.yml

For some reason nightly1's build artifact is no longer there.

ci: fix gh pages

---

addons/vscode/src/extension.ts
src/actor/editor.rs
src/actor/typst.rs
src/main.rs

feat: add control plane code to support compile status

---

addons/frontend/package.json
addons/frontend/src/svg-patch.ts
addons/frontend/yarn.lock

+ incorrect clipping to gradient filled rectangle
+ disable incremental rendering when an element contains any child with gradient.

fix: update gradient fixes

---

addons/vscode/package.json
addons/vscode/src/extension.ts
src/actor/editor.rs
src/actor/typst.rs

fix #174 and also add a full/compact status bar mode

Refactor compile status handling in VSCode

---

addons/frontend/src/svg-doc.ts

may partially fix https://github.com/Enter-tainer/typst-preview/issues/183.

fix: don't delay viewport change on cold rendering

---

addons/frontend/src/svg-doc.ts

fix a wrong variable in condition which checks whether we are not scaling content.

fix: wrong condition to allow x-axis scrolling

---

addons/frontend/index.html
addons/frontend/src/main.js
addons/frontend/src/styles/help-panel.css
addons/frontend/src/styles/layout.css
addons/frontend/src/styles/toolbar.css
addons/frontend/src/svg-doc.ts
addons/frontend/src/typst.css
addons/frontend/src/ws.ts
addons/vscode/package.json
addons/vscode/src/extension.ts
src/args.rs
src/main.rs

feat: initialize slide mode

---

addons/frontend/src/typst-doc.ts

Since last changes, the element to track is changed to parent of SVG container.

fix: scrolling scrollbar hidding

---

src/main.rs

hyper's server.await is blocking. We need spawn a new task to do so

fix preview in browser

---

addons/typst-dom/src/typst-doc.svg.mts

feat: clip page to hide overflow content

---

Cargo.lock
Cargo.toml
src/actor/editor.rs
src/actor/render.rs
src/actor/typst.rs
src/actor/webview.rs
src/await_tree.rs
src/lib.rs
src/main.rs

fix #234 
output looks like this:
```
webview actor[127.0.0.1:59604] [6.826s]
waiting for mailbox [5.317s]
waiting for websocket [5.317s]
waiting for renderer [5.317s]
editor actor [7.008s]
waiting for websocket [5.320s]
waiting for mailbox [5.320s]
render actor[127.0.0.1:59604] [6.825s]
waiting for message [5.317s]
typst actor [7.015s]
waiting for message [7.005s]
outline render actor[127.0.0.1:59604] [6.825s]
waiting for message [5.320s]
```

dev: init support for await tree

---

.github/workflows/release.yml
.vscode/tasks.json
Cargo.toml

https://doc.rust-lang.org/rustc/codegen-options/index.html#split-debuginfo
TODO:

dev: use split debug symbol

---

addons/vscode/src/extension.ts

feat: set cwd as project root

---

addons/vscode/src/extension.ts

Kill the probe task after 60 sec rather than 1 sec for testing.

dev: extend time to probe

---

.github/workflows/release.yml
.gitignore
Cargo.lock
Cargo.toml
addons/frontend/package.json
addons/frontend/yarn.lock
addons/typst-dom/package.json
addons/typst-dom/yarn.lock
addons/vscode/CHANGELOG.md
addons/vscode/README.md
addons/vscode/package.json
src/lib.rs
src/main.rs

chore: bump to v0.11.0

---

.github/workflows/release.yml
addons/vscode/src/extension.ts
addons/vscode/src/util.ts

fix: open preview in next row in 2row layout

---

addons/frontend/src/styles/layout.css

fix: scroll regression in 0.10.8

---

addons/typst-dom/src/typst-doc.svg.mts
addons/vscode/yarn.lock

fix: panic on firefox
