Enter-tainer/typst-preview

package.json, src/extension.ts, src/test/suite/extension.test.ts
Use key `typst-ws.executable` to configure typst-ws executable.
=> feat: make path to typst-ws configurable

index.html
Current behavior is if Ctrl+scroll is not used, then auto scale. Otherwise disable auto scaling on panel width change, and use a fixed table for scaling. Mouse following does not really work, removed.
=> Improve scaling

README.md
I think links would be nice so one can get directly to those repos without searching for them.
=> docs: Add links to Acknowledgements

addons/vscode/package.json, addons/vscode/src/extension.ts, addons/vscode/src/test/suite/extension.test.ts, addons/vscode/yarn.lock
The test is broken since changing `typst-ws.executable` to `typst-preview.executable`
Fix it by positive refactoring.
+ add more assertions.
+ use cross-spawn to remove hardcoded executable suffix, which also used by [eslint](https://github.com/eslint/eslint/blob/f5574dc739fcc74a7841217ba1f31cce02bee1ff/package.json#L72)
=> Fix broken test

addons/vscode/index.html
With the Remote-SSH feature of VSCode, the port used by `typst-ws` is automatically forwarded to the client (at least on Linux). However, there is a slight delay, and by the time the forwarding is set up, the WebSocket connection had already been attempted (and failed).
This PR makes the WebSocket connection retry itself when it is closed, with a delay of 1 second.
=> Retry websocket connection on close

.vscode/launch.json, Cargo.toml, addons/vscode/src/extension.ts
See discussion, https://github.com/hediet/vscode-drawio/issues/141.
> I just tested again on a new device. I've found that on my system, the issue is because VSCode's data directory is a symbolic link/junction. Unfortunately, the Scoop package installer creates the data directory this way. Probably VSCode's webview-resource protocol is not ready for this kind of configurations.
Fix it according to https://github.com/hediet/vscode-drawio/pull/152.
=> fix: load resources when they are symbolic linked

addons/vscode/src/extension.ts
Ignore `vscode.TextEditorSelectionChangeEvent` which is triggered by some commands (e. g. click the elements in the WebView and jump to source loc).
After this commit, send `panelScrollTo` request to `typst-ws` only if the selection change is taken by user's mouse or keyboard.
=> fix: panel scroll to location only if by user selection

.github/workflows/release.yml, .vscode/tasks.json, Cargo.lock, Cargo.toml, addons/vscode/package.json, addons/vscode/src/extension.ts, addons/vscode/src/test/suite/extension.test.ts, src/args.rs, src/main.rs
Rename typst-ws to typst-preview, and allow typst-preview use as a standalone binary. fix #71
=> rebrand to typst-preview and adjust cli args

Cargo.lock, Cargo.toml, README.md, addons/vscode/CHANGELOG.md, addons/vscode/README.md, addons/vscode/package.json
- Rename to Typst Preview.
- Add page level partial rendering. This should improve performance on long document. This is an experimental feature and is disabled by default. You can enable it by setting `typst-preview.partialRendering` to `true`.
- The binary `typst-preview` now can be used as a standalone typst server. You can use it to preview your document in browser. For example: `typst-preview ./assets/demo/main.typ --open-in-browser --partial-rendering`
- Fix #70: now you can launch many preview instances at the same time.
=> chore: bump to v0.6.4

Cargo.lock, Cargo.toml, addons/frontend/package.json, addons/frontend/yarn.lock, addons/vscode/CHANGELOG.md, addons/vscode/README.md, addons/vscode/package.json, addons/vscode/src/extension.ts, src/args.rs, src/main.rs
- Upgrade to typst v0.7.0
- Bug fixes
- fix #77 fix #75: Previously arm64 devices will see a blank preview. This is now fixed.
- fix #74: Previously when you open a file without opening in folder, the preview will not work. This is now fixed.
=> chore: bump to v0.7.0

.github/workflows/release.yml, addons/vscode/src/extension.ts
fix #41 
[related doc](https://code.visualstudio.com/api/advanced-topics/remote-extensions#forwarding-localhost)
> Note: Currently the forwarding mechanism in the Codespaces browser-based editor **only supports http and https requests**. However, **you can interact with any TCP connection** when connecting to a codespace from VS Code.
Since ws is based on TCP, it works.
But I didn't test whether Codespaces browser-based editor supports ws or not.
=> fix: vscode-remote support

Cargo.toml, addons/vscode/CHANGELOG.md, addons/vscode/README.md, addons/vscode/package.json
- Bug fixes:
- #79: We now put typst compiler and renderer in a dedicate thread. Therefore we should get more stable performance. 
- #78: Currently only the latest compile/render request is processed. This should fix the problem where the preview request will queue up when you type too fast and the doc takes a lot of time to compile.
- #81: We now use a more robust way to detect the whether to kill stale server process. This should fix the problem where the when preview tab will become blank when it becomes inactive for a while.
- #87: Add enum description for `typst-preview.scrollSync`. Previously the description is missing.
=> bump version to 0.7.2

addons/frontend/src/svg-patch.test.ts, addons/frontend/src/svg-patch.ts
The bug is more easily to observe with #117 not merged, because an empty main file causes single empty page to insert and then the main file recovery causes a bundle of pages to insert.
When appending pages, the svg patches become unreliable on preserving order of elements other that `<g/>`. To trigger it:
```typst
#set page(height: 60pt)
#lorem(30) // append (to ensure that fresh pages appended)
#lorem(30) // append
#lorem(30) // append
#lorem(30) // append
#lorem(30) // append
#lorem(30) // append
#text(fill: red, "123") // never patch color anymore, so it is black because of bug
#text(fill: blue, "123") // never patch color anymore, so it is black because of bug
```
Preview will have following behavior because of bug:
What is interesting is that the first element of `<svg/>` is never …
=> fix(frontend): correct `appendOffset` calculation

addons/frontend/index.html, addons/frontend/src/main.js, addons/frontend/src/svg-doc.ts, addons/frontend/src/svg-patch.ts, addons/frontend/src/svg.ts, addons/frontend/src/typst.css
Without help of upstream typst.ts, It is still easier than imagined to decorate pages.
Though we leave customization out of current PR, I believe we have a good default setting:
+ The border width is window-aware.
+ The color page's border (page break) is fixed in `--vscode-editor-background`.
+ The page's background is fixed in `white` color, but you can still override a background at typst side, as the screenshot shown.
via `set page(fill: rgb("#1a1b26").lighten(10%))`.
fix #125 fix #122 fix #80
=> dev(frontend): add height padding and center pages

src/args.rs
In #146 a version option was added. With `--version` the output looks like this:
```
typst-preview 
Build Timestamp:     2023-10-20T15:09:33.160241155Z
Build Git Discribe:  v0.8.2
Commit SHA:          Some("bfedf21f594364071003b98ff8992d34f7100a2a")
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
```
With this PR it looks more readable:
```
typst-preview 
Build Timestamp:     2023-10-20T17:25:58.472998064Z
Build Git Discribe:  v0.8.2-1-ge949869
Commit SHA:          e949869b8a2e14958ce0eb142dedf15b37acc19f
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
```
I thought about 3 or 5 different ways of unwrapping a `&'static str` from `Some()` while saving the `None` if environment variable is …
=> Removed `Some()` wrapper in output of `--version`

addons/frontend/src/svg-patch.ts
=> dev: put resources under first child of `<body/>`

addons/vscode/src/extension.ts
As discussion in #164, this is a incomplete, but simple and acceptable temporary solution for multifile project.
=> Enable sync cursor for multifile project when there is noly one preview server

addons/frontend/src/svg-doc.ts
fix #128.
Description: when somebody tries to zoom out, we has a wrong order of steps to go:
+ Initially, the viewport is at `(10000px, 0px)`, and the div element has a height of `10000px`.
+ To adjust position, js requests viewport to scroll down by `2500px`, however it hits the bottom of the div element, so it doesn't scroll down by `2500px` as expected.
+ change height of a div element to a larger value, e.g. from `10000px` to `12500px`.
Finally, the viewport is kept at the position `(10000px, 0px)` but the div element is resized to `12500px`.
If we reserve a larger height before scrolling, the wrong order steps doesn't bother.
=> fix: increase height of the SVG container before scrolling down

addons/frontend/src/svg-doc.ts
fix #185,  that holds a "height" attribute constantly would introduce weird sticky behavior on browser handling scrolling content.
=> fix: sticky scrolling

addons/vscode/README.md, addons/vscode/package.json
`ctrl+k v` is the default keybinding for "Open Markdown preview" in [vscode](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) and [markdown preview enhanced extension](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/blob/develop/package.json).
I think typst preview should also bind this shortcut to typst files, which is more convenient and can prevent some users from still using pdf preview.
=> Add keybinding `ctrl+k v` to the extension

addons/frontend/src/main.js, addons/frontend/src/styles/layout.css, addons/frontend/src/svg-debug-info.ts, addons/frontend/src/svg-doc.ts, addons/frontend/src/typst.css, addons/frontend/src/ws.ts, addons/vscode/icons/activity-bar.svg, addons/vscode/package.json, addons/vscode/src/extension.ts, src/actor/editor.rs, src/actor/mod.rs, src/actor/outline.rs, src/actor/render.rs, src/actor/webview.rs, src/main.rs
Todo: 
+ [x] Add an option to disable this feature
+ [ ] optional: change rendering mode to `canvas`
=> feat: content preview and navigation in sidebar of VSCode

addons/frontend/src/svg-animation.ts, addons/frontend/src/svg.ts
The code positions the preview panel at the top (38.2%) left (7%) of the viewport. It then detects which half of the page the user is previewing if some zoom-in scale is applied - left or right side. The preview panel's x coordinate is snapped to align with either the left or right edge of the visible page section, to ensure a suitable position.
The code only takes the single-column and 2-column layout into consideration, which has space to improvement.
1. See the picture, there are three length retrieved from DOM:
1. `1ph` is 1% height of the viewport.
2. `1pgw` is 1% width of the focused page. 
3. `1pw` is 1% width of the viewport.
2. calculate the position of the typst location as `p = (x, y)`.
3. If `viewport.width >= 90pgw || viewport.width < 50pgw`,
1. scroll to `(x - 7pw, y - …
=> dev: employ a new algorithm to handle typst location

addons/frontend/package.json, addons/frontend/src/typst-doc.ts, addons/frontend/src/typst-patch.ts, addons/frontend/src/ws.ts, addons/frontend/yarn.lock
See title. I call it mixin rendering. I don't have good names but I just name it for the sake of convention. With mixin rendering, we can heavily debounce scroll events so to make us renderer very happy. 
https://github.com/Enter-tainer/typst-preview/assets/35292584/dcffe999-8e6b-41f7-bd94-b38f9bfda050
1. You **shouldn't** change DOM heavily during scrolling event loop.
1. You **shouldn't** place too many SVG elements in window.
1. But preview has a partially rendering technique for point 2. If it doesn't rerender pages in event loop, the user will see blank pages and feel unhappy.
1. Unfortunately, the renderer changes DOM on each rendering in most common cases, failed in point 1.
I made a more aggressive "mixin rendering", which rasterizes all text elements. I call it hybrid rendering. …
=> feat: render dummy "SVG page"s as canvas pictures

addons/frontend/src/typst-doc.ts, addons/frontend/src/typst-patch.ts, addons/frontend/src/ws.ts
These are not bug but affect performance.
+ [fix: memory leak on messageData](https://github.com/Enter-tainer/typst-preview/commit/6aa682cb88c5c651363cc14dbcb6217bc579905c)
+ console.log will reference a printed data forever.
+ [fix: try to avoid change global styles](https://github.com/Enter-tainer/typst-preview/commit/ddf420310336f9cb572a9afa1d6267400961fa83) and [fix: do early rescale to avoid recalculating entire svg document](https://github.com/Enter-tainer/typst-preview/commit/01671ed7883c91ecf67c640b2c89534f37a96782)
+ try to keep styles and attributes stable, so to reduce time on recalculating too many DOM elements.
=> fix: memory leak and DOM recalculation

addons/vscode/CHANGELOG.md
Improves the CHANGELOG.md file:
- Reorder all entries so that the most recent change is shown first - no need to scroll to the bottom for interesting stuff. This principle is also mentioned in https://keepachangelog.com/en/1.1.0/ and most VSCode extensions follow that.
- Adds dates to versions. (Dates taken from commit history).
- Adds a `v` prefix to all version numbers: `v0.1.0`
- Fixes some minor linting issues.
If needed, I can make some or all changes also to the list in `README.md`.
=> Improve changelog

Cargo.lock, Cargo.toml, addons/frontend/package.json, addons/frontend/src/typst.css, addons/frontend/yarn.lock, addons/typst-dom/package.json, addons/typst-dom/src/typst-debug-info.mts, addons/typst-dom/src/typst-doc.mts, addons/typst-dom/src/typst-doc.svg.mts, addons/typst-dom/src/typst-outline.mts, addons/typst-dom/src/typst-patch.mts, addons/typst-dom/src/typst-patch.svg.mts, addons/typst-dom/src/typst-patch.test.mts, addons/typst-dom/yarn.lock, addons/vscode/yarn.lock, src/actor/render.rs, src/actor/typst.rs, src/actor/webview.rs, src/lib.rs
+ fix a bug that fails to incrementally rendering pages with transformed content. https://github.com/Myriad-Dreamin/typst.ts/pull/443.
+ fix a glyph data desync problem, corrupting state of webview typically after **your editor hibernating and coming back**. https://github.com/Myriad-Dreamin/typst.ts/pull/452 and https://github.com/Myriad-Dreamin/typst.ts/pull/459.
+ export vector IR (the binary data transferring to webview) in parallel. hhttps://github.com/Myriad-Dreamin/typst.ts/pull/459.
+ export span information in parallel. It also doesn't transfer to webview side anymore, solving unsafe span casting and improving performance. https://github.com/Myriad-Dreamin/typst.ts/pull/459.
=> dev: upgrade typst.ts to v0.4.2-rc5

Cargo.lock, Cargo.toml, addons/frontend/package.json, addons/frontend/src/typst.css, addons/frontend/src/ws.ts, addons/frontend/yarn.lock, addons/typst-dom/package.json, addons/typst-dom/src/typst-debug-info.mts, addons/typst-dom/src/typst-doc.svg.mts, addons/typst-dom/yarn.lock, addons/vscode/src/extension.ts, src/actor/render.rs, src/actor/typst.rs, src/actor/webview.rs, src/lib.rs
Previous, cursor position are represented by `page,x,y` generated by `jump_from_cursor`, but it is a bit coarse. Now, we change the approach a bit, which contains several steps:
+ editor extension reports a cursor change event, containing (file, line, column) of the cursor.
+ editor actor receives it and pass it to typst actor.
+ typst actor finds a corresponding (span, inner-offset) by (file, line, column).
+ typst actor locks the world, and finds a span with inner byte offset in the source file's AST.
+ typst send change cursor request to renderer, containing (span, inner-offset) of the cursor.
+ renderer actor finds the corresponding element paths (path from vector IR's root to some leaf) by (span, inner-offset).
+ it queries all leaves owning `span`. If there is a inner-offset, it …
=> feat: make cursor positions accurate

addons/frontend/src/typst.css, addons/frontend/src/ws.ts, addons/vscode/package.json, addons/vscode/src/extension.ts, src/args.rs, src/lib.rs
Provides an option:
```jsonc
"typst-preview.invertColors": {
"description": "Invert colors of the preview (useful for dark themes without cost). Please note you could see the origin colors when you hover elements in the preview.",
"type": "string",
"enum": [
"never",
"auto",
"always"
],
"default": "never",
"enumDescriptions": [
"Disable color inversion of the preview",
"Invert colors smartly by detecting dark/light themes in browser environment or by `typst query` your document",
"Always invert colors of the preview"
]
}
```
It inverts all color of items, but when you hover on images, they are back to origin color to help read content inside.
The `` `typst query` your document `` in auto is not implemented but I want to leave it in the initial feature PR, to remind users you can wait for …
=> feat: get dark theme for free by the `invert-colors` option

addons/vscode/package.json, addons/vscode/src/extension.ts
The description `onSelectionChange` is bad, since it is actually "when selection changes by mouse", but we may keep compability. Regardless of compability, the perfect enums are probably:
```
"onSelectionChange" -> "onSelectionChangeByMouse"
"onAnyChange" -> "onSelectionChange"
```
=> feat: auto scroll sync by keyboard events

addons/vscode/package.json, addons/vscode/src/extension.ts, addons/vscode/tsconfig.json
1. use spawnSync to test exec
2. make test result more informative
3. add version checking, ensure extension and binary are of the same version
fix #235
=> dev: use spawnSync to test exec and add version checking

docs/arch.typ, docs/book.typ, docs/intro.typ
Found via `typos --hidden --format brief`
=> chore: fix typos

.github/workflows/release.yml, Cargo.toml
see https://github.com/rust-lang/rust/issues/105991 and https://github.com/rust-lang/rust/issues/34651#issuecomment-1253008705. also https://maskray.me/blog/2022-10-30-distribution-of-debug-information and https://internals.rust-lang.org/t/help-test-faster-incremental-debug-macos-builds-on-nightly/14016
=> dev: use objcopy to generate split debug symbol

addons/typst-dom/src/typst-doc.mts
fix #238 fix #208
I just randomly choose a threshold, and currently I don't have a mouse. Please test!
=> fix sensitive scale on touchpad

addons/typst-dom/src/typst-doc.mts, addons/typst-dom/src/typst-doc.svg.mts
fix #223. `await ctoken.wait();` may cause a new "animation frame", and result in view jumps, because of a zooming operation finishes in multiple frames.
This PR move the cancellation into the svg rerendering, and await the cancellation in deferred update.
=> fix: don't block rerender procedure

addons/vscode/package.json
see https://github.com/microsoft/vscode/issues/49145
fix #287
=> fix: show activity bar icon only when current res is typst

addons/vscode/package.json, addons/vscode/src/extension.ts, src/args.rs, src/main.rs
In the cli, the argument is the same as typst cli, which is `--input key=value --input key2=value2 ...`.
However, I'm unsure about how to name the configuration in the VSCode extension. Calling it simply `typst-preview.inputs` seems ambiguous. For now, I'm using `typst-preview.typstInputs`, which can be revised based on further discussion.(Change to `typst-preview.sysInputs`)
I think this could close #213.
=> Add supports for setting sys.inputs

addons/vscode/package.json, addons/vscode/src/extension.ts, addons/vscode/src/test/suite/extension.test.ts, src/args.rs, src/main.rs
Another small option which gives more control over compilation environment.
According to typst/typst#4227, the official designation for this argument has been confirmed as `--ignore-system-fonts`. We follow it in cli argument. In extension, added a `typst-preview.systemFonts` configuration to control it.
Besides, since there is no clear use case for utilizing VSCode variables within sys.input, this PR disables it.
=> feat: option to ignore system fonts when previewing

addons/frontend/index.html, addons/frontend/src/main.js, addons/vscode/package.json, addons/vscode/src/extension.ts
Hello!
This is a small PR implementing the [serialization](https://code.visualstudio.com/api/extension-guides/webview#serialization) feature which lets the webviews persist over VSCode restarts :)
To see its effect, try opening up a Typst Preview inside VSCode, then run the "Developer: Reload Window" command or close and open VSCode. Before this PR, the Typst Preview would cease to exist. After it, it should re-load.
=> Persist webview preview through vscode restarts
